import {
    ArchiveIcon,
    AssignmentIcon,
    AssignmentOutlineIcon,
    BackIcon,
    BadgeIcon,
    BellIcon,
    BellOutlineIcon,
    CalendarBlankOutlineIcon,
    CalendarIcon,
    CalendarRangeIcon,
    CalendarRangeOutlineIcon,
    CheckBoxCheckedIcon,
    CheckFactIcon,
    CheckFactOutlineIcon,
    CheckIcon,
    CheckOutlineIcon,
    ChevronDoubleLeftIcon,
    ChevronDoubleRightIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ClockOutlineIcon,
    CloseIcon,
    ConsentsIcon,
    DashboardViewIcon,
    DashboardViewOutlineIcon,
    DeleteOutlineIcon,
    DoneAllIcon,
    DotsVerticalIcon,
    DownloadIcon,
    DragHorizontalIcon,
    DropDownIcon,
    DropUpIcon,
    DvrIcon,
    EarthIcon,
    EditSquareIcon,
    EmptyPageIcon,
    ErrorOutlineIcon,
    FastCheckOutlineIcon,
    FilePdfIcon,
    FilterIcon,
    FindReplaceIcon,
    FindReplacePeopleIcon,
    FormIcon,
    HamburgerIcon,
    HandymanIcon,
    HandymanOutlineIcon,
    HelpIcon,
    HelpOutlineIcon,
    InboxOutboxIcon,
    InboxOutboxOutlineIcon,
    KeyboardCapslockIcon,
    LinkOutlineIcon,
    ListNumberedIcon,
    ListSettingsLineIcon,
    ListStatusIcon,
    LoadingIcon,
    LocationIcon,
    LockIcon,
    LoginIcon,
    LogoutIcon,
    MessageProcessingIcon,
    MessageProcessingOutlineIcon,
    MessageReplyIcon,
    MicrosoftOutlookIcon,
    MinimizeIcon,
    NewCalendarIcon,
    NewWindowIcon,
    OutlineCalendarMonth,
    PdfIcon,
    PencilOutlineIcon,
    PeopleIcon,
    PeopleOutlineIcon,
    PermMediaIcon,
    PermMediaOutline,
    PersonIcon,
    PersonOutlineIcon,
    PinIcon,
    PlusIcon,
    PlusIconCircle,
    QnrIcon,
    RepeatOutlineIcon,
    ReplayIcon,
    ReportBoxIcon,
    ReportBoxOutlineIcon,
    SearchIcon,
    SettingsIcon,
    SettingsMenuHorizontalIcon,
    SettingsOutlineIcon,
    TextBoxCheckOutlineIcon,
    TimerIcon,
    TodayIcon,
    TopicIcon,
    UnknownDocumentOutlineRoundedIcon,
    UnlockIcon,
    WarningAmberOutlineIcon,
    WorkIcon,
    DescriptionIcon,
    DescriptionOutlineIcon,
    DnsOutlineIcon,
    DnsIcon,
    RuleIcon,
    RuleOutlineIcon,
    FormatListBulletedIcon,
    FormatListBulletedOutlineIcon,
    PersonSearchIcon,
    PersonSearchOutlineIcon,
    ContentCopyIcon,
    ContentCopyOutlineIcon,
    RefreshIcon,
    SettingsNoteIcon,
    InheritancePointerIcon,
    CloudDoneOutlineIcon,
    AttachFileIcon,
    SendIcon,
} from 'src/components/icons'

export const useIconsList = ({ filterText, height, width }: { filterText: string; height: number; width: number }) => {
    const icons = [
        {
            name: 'HelpIcon',
            component: <HelpIcon height={height} width={width} />,
            clipboardText: '<HelpIcon />',
            tags: ['help'],
        },
        {
            name: 'HelpOutlineIcon',
            component: <HelpOutlineIcon height={height} width={width} />,
            clipboardText: '<HelpOutlineIcon />',
            tags: ['help outline'],
        },
        {
            name: 'LoadingIcon',
            component: <LoadingIcon height={height} width={width} />,
            clipboardText: '<LoadingIcon />',
            tags: ['loading'],
        },
        {
            name: 'DownloadIcon',
            component: <DownloadIcon height={height} width={width} />,
            clipboardText: '<DownloadIcon />',
            tags: ['download'],
        },
        {
            name: 'ArchiveIcon',
            component: <ArchiveIcon height={height} width={width} />,
            clipboardText: '<ArchiveIcon />',
            tags: ['archive'],
        },
        {
            name: 'DotsVerticalIcon',
            component: <DotsVerticalIcon height={height} width={width} />,
            clipboardText: '<DotsVerticalIcon />',
            tags: ['dots'],
        },
        {
            name: 'FindReplaceIcon',
            component: <FindReplaceIcon height={height} width={width} />,
            clipboardText: '<FindReplaceIcon />',
            tags: ['find replace'],
        },
        {
            name: 'FindReplacePeopleIcon',
            component: <FindReplacePeopleIcon className='w-[26px] h-[26px]' />,
            clipboardText: '<FindReplacePeopleIcon />',
            tags: ['find replace people'],
        },
        {
            name: 'SearchIcon',
            component: <SearchIcon height={height} width={width} />,
            clipboardText: '<SearchIcon />',
            tags: ['search'],
        },
        {
            name: 'SettingsOutlineIcon',
            component: <SettingsOutlineIcon height={height} width={width} />,
            clipboardText: '<SettingsOutlineIcon />',
            tags: ['settings outline'],
        },
        {
            name: 'SettingsIcon',
            component: <SettingsIcon height={height} width={width} />,
            clipboardText: '<SettingsIcon />',
            tags: ['settings'],
        },
        {
            name: 'ReportBoxOutlineIcon',
            component: <ReportBoxOutlineIcon height={height} width={width} />,
            clipboardText: '<ReportBoxOutlineIcon />',
            tags: ['report box outline'],
        },
        {
            name: 'ReportBoxIcon',
            component: <ReportBoxIcon height={height} width={width} />,
            clipboardText: '<ReportBoxIcon />',
            tags: ['report box'],
        },
        {
            name: 'BellOutlineIcon',
            component: <BellOutlineIcon height={height} width={width} color='orange' />,
            clipboardText: '<BellOutlineIcon />',
            tags: ['bell outline'],
        },
        {
            name: 'BellIcon',
            component: <BellIcon height={height} width={width} color='orange' />,
            clipboardText: '<BellIcon />',
            tags: ['bell'],
        },
        {
            name: 'HamburgerIcon',
            component: <HamburgerIcon height={height} width={width} />,
            clipboardText: '<HamburgerIcon />',
            tags: ['hamburger'],
        },
        {
            name: 'PdfIcon',
            component: <PdfIcon height={height} width={width} color='red' />,
            clipboardText: '<PdfIcon />',
            tags: ['pdf'],
        },
        {
            name: 'QnrIcon',
            component: <QnrIcon height={height} width={width} color='blue' />,
            clipboardText: '<QnrIcon />',
            tags: ['qnr'],
        },
        {
            name: 'DropUpIcon',
            component: <DropUpIcon height={height} width={width} />,
            clipboardText: '<DropUpIcon />',
            tags: ['drop up'],
        },
        {
            name: 'DropDownIcon',
            component: <DropDownIcon height={height} width={width} />,
            clipboardText: '<DropDownIcon />',
            tags: ['drop down'],
        },
        {
            name: 'ChevronDownIcon',
            component: <ChevronDownIcon height={height} width={width} />,
            clipboardText: '<ChevronDownIcon />',
            tags: ['chevron down'],
        },
        {
            name: 'ChevronUpIcon',
            component: <ChevronUpIcon height={height} width={width} />,
            clipboardText: '<ChevronUpIcon />',
            tags: ['chevron up'],
        },
        {
            name: 'ChevronLeftIcon',
            component: <ChevronLeftIcon height={height} width={width} />,
            clipboardText: '<ChevronLeftIcon />',
            tags: ['chevron left'],
        },
        {
            name: 'ChevronRightIcon',
            component: <ChevronRightIcon height={height} width={width} />,
            clipboardText: '<ChevronRightIcon />',
            tags: ['chevron right'],
        },
        {
            name: 'ChevronDoubleRightIcon',
            component: <ChevronDoubleRightIcon height={height} width={width} />,
            clipboardText: '<ChevronDoubleRightIcon />',
            tags: ['chevron double right'],
        },
        {
            name: 'ChevronDoubleLeftIcon',
            component: <ChevronDoubleLeftIcon height={height} width={width} />,
            clipboardText: '<ChevronDoubleLeftIcon />',
            tags: ['chevron double left'],
        },
        {
            name: 'DashboardViewOutlineIcon',
            component: <DashboardViewOutlineIcon height={height} width={width} />,
            clipboardText: '<DashboardViewOutlineIcon />',
            tags: ['dashboard view outline'],
        },
        {
            name: 'DashboardViewIcon',
            component: <DashboardViewIcon height={height} width={width} />,
            clipboardText: '<DashboardViewIcon />',
            tags: ['dashboard view'],
        },
        {
            name: 'PersonIcon',
            component: <PersonIcon height={height} width={width} />,
            clipboardText: '<PersonIcon />',
            tags: ['person'],
        },
        {
            name: 'PersonOutlineIcon',
            component: <PersonOutlineIcon height={height} width={width} />,
            clipboardText: '<PersonOutlineIcon />',
            tags: ['person outline'],
        },
        {
            name: 'PeopleOutlineIcon',
            component: <PeopleOutlineIcon height={height} width={width} />,
            clipboardText: '<PeopleOutlineIcon />',
            tags: ['people outline'],
        },
        {
            name: 'PeopleIcon',
            component: <PeopleIcon height={height} width={width} />,
            clipboardText: '<PeopleIcon />',
            tags: ['people'],
        },
        {
            name: 'CloseIcon',
            component: <CloseIcon height={height} width={width} />,
            clipboardText: '<CloseIcon />',
            tags: ['close'],
        },
        {
            name: 'CheckIcon',
            component: <CheckIcon height={height} width={width} color='green' />,
            clipboardText: '<CheckIcon />',
            tags: ['check'],
        },
        {
            name: 'CheckBoxCheckedIcon',
            component: <CheckBoxCheckedIcon height={height} width={width} color='green' />,
            clipboardText: '<CheckBoxCheckedIcon />',
            tags: ['check box checked'],
        },
        {
            name: 'CheckOutlineIcon',
            component: <CheckOutlineIcon height={height} width={width} color='green' />,
            clipboardText: '<CheckOutlineIcon />',
            tags: ['check outline'],
        },
        {
            name: 'CheckFactOutlineIcon',
            component: <CheckFactOutlineIcon height={height} width={width} color='green' />,
            clipboardText: '<CheckFactOutlineIcon />',
            tags: ['check fact outline'],
        },
        {
            name: 'CheckFactIcon',
            component: <CheckFactIcon height={height} width={width} color='green' />,
            clipboardText: '<CheckFactIcon />',
            tags: ['check fact'],
        },
        {
            name: 'CalendarIcon',
            component: <CalendarIcon height={height} width={width} />,
            clipboardText: '<CalendarIcon />',
            tags: ['calendar'],
        },
        {
            name: 'CalendarRangeIcon',
            component: <CalendarRangeIcon height={height} width={width} />,
            clipboardText: '<CalendarRangeIcon />',
            tags: ['calendar range'],
        },
        {
            name: 'CalendarRangeOutlineIcon',
            component: <CalendarRangeOutlineIcon height={height} width={width} />,
            clipboardText: '<CalendarRangeOutlineIcon />',
            tags: ['calendar range outline'],
        },
        {
            name: 'TodayIcon',
            component: <TodayIcon height={height} width={width} />,
            clipboardText: '<TodayIcon />',
            tags: ['today'],
        },
        {
            name: 'CalendarBlankOutlineIcon',
            component: <CalendarBlankOutlineIcon height={height} width={width} />,
            clipboardText: '<CalendarBlankOutlineIcon />',
            tags: ['calendar blank outline'],
        },
        {
            name: 'OutlineCalendarMonth',
            component: <OutlineCalendarMonth height={height} width={width} />,
            clipboardText: '<OutlineCalendarMonth />',
            tags: ['outline calendar'],
        },
        {
            name: 'NewCalendarIcon',
            component: <NewCalendarIcon height={height} width={width} />,
            clipboardText: '<NewCalendarIcon />',
            tags: ['new calendar'],
        },
        {
            name: 'AssignmentOutlineIcon',
            component: <AssignmentOutlineIcon height={height} width={width} />,
            clipboardText: '<AssignmentOutlineIcon />',
            tags: ['assignment outline'],
        },
        {
            name: 'AssignmentIcon',
            component: <AssignmentIcon height={height} width={width} />,
            clipboardText: '<AssignmentIcon />',
            tags: ['assignment'],
        },
        {
            name: 'ListNumberedIcon',
            component: <ListNumberedIcon height={height} width={width} />,
            clipboardText: '<ListNumberedIcon />',
            tags: ['list numbered'],
        },
        {
            name: 'MessageProcessingIcon',
            component: <MessageProcessingIcon height={height} width={width} />,
            clipboardText: '<MessageProcessingIcon />',
            tags: ['message processing'],
        },
        {
            name: 'MessageProcessingOutlineIcon',
            component: <MessageProcessingOutlineIcon height={height} width={width} />,
            clipboardText: '<MessageProcessingOutlineIcon />',
            tags: ['message processing outline'],
        },
        {
            name: 'PermMediaIcon',
            component: <PermMediaIcon height={height} width={width} />,
            clipboardText: '<PermMediaIcon />',
            tags: ['perm media'],
        },
        {
            name: 'PermMediaOutline',
            component: <PermMediaOutline height={height} width={width} />,
            clipboardText: '<PermMediaOutline />',
            tags: ['perm media'],
        },
        {
            name: 'ClockOutlineIcon',
            component: <ClockOutlineIcon height={height} width={width} />,
            clipboardText: '<ClockOutlineIcon />',
            tags: ['clock outline'],
        },
        {
            name: 'InboxOutboxIcon',
            component: <InboxOutboxIcon height={height} width={width} />,
            clipboardText: '<InboxOutboxIcon />',
            tags: ['inbox outbox'],
        },
        {
            name: 'InboxOutboxOutlineIcon',
            component: <InboxOutboxOutlineIcon height={height} width={width} />,
            clipboardText: '<InboxOutboxOutlineIcon />',
            tags: ['inbox outbox outline'],
        },
        {
            name: 'TopicIcon',
            component: <TopicIcon height={height} width={width} />,
            clipboardText: '<TopicIcon />',
            tags: ['topic'],
        },
        {
            name: 'EmptyPageIcon',
            component: <EmptyPageIcon height={height} width={width} />,
            clipboardText: '<EmptyPageIcon />',
            tags: ['empty page'],
        },
        {
            name: 'DragHorizontalIcon',
            component: <DragHorizontalIcon height={height} width={width} />,
            clipboardText: '<DragHorizontalIcon />',
            tags: ['drag horizontal'],
        },
        {
            name: 'FilePdfIcon',
            component: <FilePdfIcon height={height} width={width} color='red' />,
            clipboardText: '<FilePdfIcon />',
            tags: ['file pdf'],
        },
        {
            name: 'DeleteOutlineIcon',
            component: <DeleteOutlineIcon height={height} width={width} />,
            clipboardText: '<DeleteOutlineIcon />',
            tags: ['delete outline'],
        },
        {
            name: 'FilterIcon',
            component: <FilterIcon height={height} width={width} />,
            clipboardText: '<FilterIcon />',
            tags: ['filter'],
        },
        {
            name: 'LockIcon',
            component: <LockIcon height={height} width={width} />,
            clipboardText: '<LockIcon />',
            tags: ['lock'],
        },
        {
            name: 'DvrIcon',
            component: <DvrIcon height={height} width={width} />,
            clipboardText: '<DvrIcon />',
            tags: ['dvr'],
        },
        {
            name: 'ErrorOutlineIcon',
            component: <ErrorOutlineIcon height={height} width={width} />,
            clipboardText: '<ErrorOutlineIcon />',
            tags: ['error outline'],
        },
        {
            name: 'ReplayIcon',
            component: <ReplayIcon height={height} width={width} />,
            clipboardText: '<ReplayIcon />',
            tags: ['replay'],
        },
        {
            name: 'LinkOutlineIcon',
            component: <LinkOutlineIcon height={height} width={width} />,
            clipboardText: '<LinkOutlineIcon />',
            tags: ['link outline'],
        },
        {
            name: 'FastCheckOutlineIcon',
            component: <FastCheckOutlineIcon height={height} width={width} />,
            clipboardText: '<FastCheckOutlineIcon />',
            tags: ['fast check outline'],
        },
        {
            name: 'UnknownDocumentOutlineRoundedIcon',
            component: <UnknownDocumentOutlineRoundedIcon height={height} width={width} />,
            clipboardText: '<UnknownDocumentOutlineRoundedIcon />',
            tags: ['unknown document outline rounded'],
        },
        {
            name: 'ListStatusIcon',
            component: <ListStatusIcon height={height} width={width} />,
            clipboardText: '<ListStatusIcon />',
            tags: ['list status'],
        },
        {
            name: 'TextBoxCheckOutlineIcon',
            component: <TextBoxCheckOutlineIcon height={height} width={width} />,
            clipboardText: '<TextBoxCheckOutlineIcon />',
            tags: ['text box check outline'],
        },
        {
            name: 'ListSettingsLineIcon',
            component: <ListSettingsLineIcon height={height} width={width} />,
            clipboardText: '<ListSettingsLineIcon />',
            tags: ['list settings line'],
        },
        {
            name: 'EarthIcon',
            component: <EarthIcon height={height} width={width} />,
            clipboardText: '<EarthIcon />',
            tags: ['earth'],
        },
        {
            name: 'SettingsMenuHorizontalIcon',
            component: <SettingsMenuHorizontalIcon height={height} width={width} />,
            clipboardText: '<SettingsMenuHorizontalIcon />',
            tags: ['settings menu horizontal'],
        },
        {
            name: 'PencilOutlineIcon',
            component: <PencilOutlineIcon height={height} width={width} />,
            clipboardText: '<PencilOutlineIcon />',
            tags: ['pencil outline'],
        },
        {
            name: 'WarningAmberOutlineIcon',
            component: <WarningAmberOutlineIcon height={height} width={width} color='red' />,
            clipboardText: '<WarningAmberOutlineIcon />',
            tags: ['warning amber outline'],
        },
        {
            name: 'ConsentsIcon',
            component: <ConsentsIcon height={height} width={width} />,
            clipboardText: '<ConsentsIcon />',
            tags: ['consents'],
        },
        {
            name: 'MinimizeIcon',
            component: <MinimizeIcon height={height} width={width} />,
            clipboardText: '<MinimizeIcon />',
            tags: ['minimize'],
        },
        {
            name: 'KeyboardCapslockIcon',
            component: <KeyboardCapslockIcon height={height} width={width} />,
            clipboardText: '<KeyboardCapslockIcon />',
            tags: ['keyboard capslock'],
        },
        {
            name: 'MessageReplyIcon',
            component: <MessageReplyIcon height={height} width={width} />,
            clipboardText: '<MessageReplyIcon />',
            tags: ['message reply'],
        },
        {
            name: 'BadgeIcon',
            component: <BadgeIcon height={height} width={width} />,
            clipboardText: '<BadgeIcon />',
            tags: ['badge'],
        },
        {
            name: 'EditSquareIcon',
            component: <EditSquareIcon height={height} width={width} />,
            clipboardText: '<EditSquareIcon />',
            tags: ['edit square'],
        },
        {
            name: 'PlusIcon',
            component: <PlusIcon height={height} width={width} />,
            clipboardText: '<PlusIcon />',
            tags: ['plus'],
        },
        {
            name: 'PlusIconCircle',
            component: <PlusIconCircle height={height} width={width} />,
            clipboardText: '<PlusIconCircle />',
            tags: ['plus circle'],
        },
        {
            name: 'HandymanOutlineIcon',
            component: <HandymanOutlineIcon height={height} width={width} />,
            clipboardText: '<HandymanOutlineIcon />',
            tags: ['handyman outline'],
        },
        {
            name: 'PinIcon',
            component: <PinIcon height={height} width={width} />,
            clipboardText: '<PinIcon />',
            tags: ['pin'],
        },
        {
            name: 'WorkIcon',
            component: <WorkIcon height={height} width={width} />,
            clipboardText: '<WorkIcon />',
            tags: ['work'],
        },
        {
            name: 'LocationIcon',
            component: <LocationIcon height={height} width={width} />,
            clipboardText: '<LocationIcon />',
            tags: ['location'],
        },
        {
            name: 'FormIcon',
            component: <FormIcon height={height} width={width} />,
            clipboardText: '<FormIcon />',
            tags: ['form'],
        },
        {
            name: 'RepeatOutlineIcon',
            component: <RepeatOutlineIcon height={height} width={width} />,
            clipboardText: '<RepeatOutlineIcon />',
            tags: ['repeat outline'],
        },
        {
            name: 'MicrosoftOutlookIcon',
            component: <MicrosoftOutlookIcon height={height} width={width} color='blue' />,
            clipboardText: '<MicrosoftOutlookIcon />',
            tags: ['microsoft outlook'],
        },
        {
            name: 'LoginIcon',
            component: <LoginIcon height={height} width={width} />,
            clipboardText: '<LoginIcon />',
            tags: ['login'],
        },
        {
            name: 'LogoutIcon',
            component: <LogoutIcon height={height} width={width} />,
            clipboardText: '<LogoutIcon />',
            tags: ['logout'],
        },
        {
            name: 'TimerIcon',
            component: <TimerIcon height={height} width={width} />,
            clipboardText: '<TimerIcon />',
            tags: ['timer'],
        },
        {
            name: 'BackIcon',
            component: <BackIcon height={height} width={width} />,
            clipboardText: '<BackIcon />',
            tags: ['back'],
        },
        {
            name: 'NewWindowIcon',
            component: <NewWindowIcon height={height} width={width} />,
            clipboardText: '<NewWindowIcon />',
            tags: ['new window'],
        },
        {
            name: 'DoneAllIcon',
            component: <DoneAllIcon height={height} width={width} />,
            clipboardText: '<DoneAllIcon />',
            tags: ['done all'],
        },
        {
            name: 'UnlockIcon',
            component: <UnlockIcon height={height} width={width} />,
            clipboardText: '<UnlockIcon />',
            tags: ['Unlock'],
        },
        {
            name: 'DescriptionIcon',
            component: <DescriptionIcon height={height} width={width} />,
            clipboardText: '<DescriptionIcon />',
            tags: ['description '],
        },
        {
            name: 'DescriptionOutlineIcon',
            component: <DescriptionOutlineIcon height={height} width={width} />,
            clipboardText: '<DescriptionOutlineIcon />',
            tags: ['description outline'],
        },

        {
            name: 'DnsIcon',
            component: <DnsIcon height={height} width={width} />,
            clipboardText: '<DnsIcon />',
            tags: ['dns '],
        },
        {
            name: 'DnsOutlineIcon',
            component: <DnsOutlineIcon height={height} width={width} />,
            clipboardText: '<DnsOutlineIcon />',
            tags: ['dns outline'],
        },
        {
            name: 'RuleIcon',
            component: <RuleIcon height={height} width={width} />,
            clipboardText: '<RuleIcon />',
            tags: ['rule '],
        },
        {
            name: 'RuleOutlineIcon',
            component: <RuleOutlineIcon height={height} width={width} />,
            clipboardText: '<RuleOutlineIcon />',
            tags: ['rule outline'],
        },
        {
            name: 'FormatListBulletedIcon',
            component: <FormatListBulletedIcon height={height} width={width} />,
            clipboardText: '<FormatListBulletedIcon />',
            tags: ['format list bulleted'],
        },
        {
            name: 'FormatListBulletedOutlineIcon',
            component: <FormatListBulletedOutlineIcon height={height} width={width} />,
            clipboardText: '<FormatListBulletedOutlineIcon />',
            tags: ['format list bulleted outline'],
        },
        {
            name: 'PersonSearchIcon',
            component: <PersonSearchIcon height={height} width={width} />,
            clipboardText: '<PersonSearchIcon />',
            tags: ['person search '],
        },
        {
            name: 'PersonSearchOutlineIcon',
            component: <PersonSearchOutlineIcon height={height} width={width} />,
            clipboardText: '<PersonSearchOutlineIcon />',
            tags: ['person search outline'],
        },
        {
            name: 'ContentCopyIcon',
            component: <ContentCopyIcon height={height} width={width} />,
            clipboardText: '<ContentCopyIcon />',
            tags: ['content copy '],
        },
        {
            name: 'ContentCopyOutlineIcon',
            component: <ContentCopyOutlineIcon height={height} width={width} />,
            clipboardText: '<ContentCopyOutlineIcon />',
            tags: ['content copy outline'],
        },
        {
            name: 'RefreshIcon',
            component: <RefreshIcon height={height} width={width} />,
            clipboardText: '<RefreshIcon />',
            tags: ['refresh '],
        },
        {
            name: 'SettingsNoteIcon',
            component: <SettingsNoteIcon height={height} width={width} />,
            clipboardText: '<SettingsNoteIcon />',
            tags: ['settings-note'],
        },
        {
            name: 'InheritancePointerIcon',
            component: <InheritancePointerIcon height={height} width={width} />,
            clipboardText: '<InheritancePointerIcon />',
            tags: ['inheritance-pointer'],
        },
        {
            name: 'CloudDoneOutlineIcon',
            component: <CloudDoneOutlineIcon height={height} width={width} />,
            clipboardText: '<CloudDoneOutlineIcon />',
            tags: ['cloud done outline'],
        },
        {
            name: 'AttachFileIcon',
            component: <AttachFileIcon height={height} width={width} />,
            clipboardText: '<AttachFileIcon />',
            tags: ['attach file outline'],
        },
        {
            name: 'SendIcon',
            component: <SendIcon height={height} width={width} />,
            clipboardText: '<SendIcon />',
            tags: ['send icon'],
        },
    ]

    const filteredIcons = icons.filter(
        (icon) =>
            icon.name.trim().toLowerCase().includes(filterText.toLowerCase().trim()) ||
            icon.tags.some((tag) => tag.trim().toLowerCase().includes(filterText.toLowerCase().trim())),
    )

    return {
        icons: filteredIcons,
    }
}
